name: Upload artifact

on:
  push:
    branches:
      - main

jobs:
  upload:
    name: Generate nuget package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    - run: dotnet workload restore
    - name: Build
      run: dotnet build
    - name: Publish
      run: dotnet publish
    - name: Push to GitHub Packages
      run: dotnet nuget add source --username orskovacs --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/orskovacs/index.json"
