name: Upload artifact

on:
  push:
    branches:
      - main

jobs:
  upload:
    name: Generate Build Artifacts
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup dotnet
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
    - run: dotnet workload restore
    - name: Build
      run: dotnet build
    - name: Publish
      run: dotnet publish
    - name: Upload
      uses: actions/upload-artifact@v4.5.0
      with:
        name: verifier
        path: EbDbaLsDtw/bin/Release/EbDbaLsDtw.*.nupkg
        if-no-files-found: error
        overwrite: true
